[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "coshui"
version = "0.3.3"
authors = [{name = "Jyle Frazier Villareal", email = "jylefraziervillareal@gmail.com"}]
description = "A Python-first — Declarative-Mode — Backend-Agnostic — UI Library"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: User Interfaces",
    "Topic :: Games/Entertainment",
]

[project.optional-dependencies]
pygame = ["pygame-ce"]
raylib = ["raylibpy"]
moderngl = ["moderngl", "glfw", "freetype-py", "Pillow"]
moderngl-mglw = ["moderngl", "moderngl-window", "freetype-py", "Pillow"]
pyopengl = ["PyOpenGL", "PyOpenGL_accelerate", "glfw", "freetype-py", "Pillow"]
all = ["pygame-ce", "raylibpy", "PyOpenGL", "PyOpenGL_accelerate", "glfw", "moderngl", "moderngl-window", "freetype-py", "Pillow"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
coshui = [
    "assets/fonts/*.ttf",
    "backends/graphics/gl_related/glsl/*.frag",
    "backends/graphics/gl_related/glsl/*.vert"
]

[project.urls]
Homepage = "https://terrarizer03.github.io/coshui-docs/"
Repository = "https://gitlab.com/JyleFV/CoshUI"
Issues = "https://gitlab.com/JyleFV/CoshUI/-/issues"
Documentation = "https://terrarizer03.github.io/coshui-docs"