[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "coshui"
version = "0.2.4"
authors = [{name = "Jyle Frazier Villareal", email = "jylefraziervillareal@gmail.com"}]
description = "A Python-first — Declarative-Mode — Backend-Agnostic — UI Library"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: User Interfaces",
    "Topic :: Games/Entertainment",
]

[project.optional-dependencies]
pygame = ["pygame-ce"]
raylib = ["raylib-py"]
all = ["pygame-ce", "raylib-py"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
coshui = ["assets/fonts/*.ttf"]

[project.urls]
Homepage = "https://terrarizer03.github.io/coshui-docs/"
Repository = "https://gitlab.com/JyleFV/CoshUI"
Issues = "https://gitlab.com/JyleFV/CoshUI/-/issues"
Documentation = "https://terrarizer03.github.io/coshui-docs"